site_lists = [
    # {
    #     'scid': 2113,
    #     'table_name': 'account_executive',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    #     'sub_category': 'Account Executive Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Account-Executive',
    # },
    # {
    #     'scid': 1901,
    #     'table_name': 'account_management',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    #     'sub_category': 'Account Management Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Management-Accountant',
    # },
    # {
    #     'scid': 36,
    #     'table_name': 'accounting',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    #     'sub_category': 'Accounting Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Accounting',
    # },
    # {
    #     'scid': 2114,
    #     'table_name': 'accounting_manager',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    #     'sub_category': 'Accounting Manager Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Accounting-Manager',
    # },
    # {
    #     'scid': 95,
    #     'table_name': 'accounts_payable',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    #     'sub_category': 'Accounts Payable Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Accounts-Payable',
    # },
    # {
    #     'scid': 2115,
    #     'table_name': 'accounts_receivable_clerk',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    #     'sub_category': 'Accounts Receivable Clerk Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Accounts-Receivable-Clerk',
    # },
    # {
    #     'scid': 2116,
    #     'table_name': 'advertising_account_executive',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    #     'sub_category': 'Advertising Account Executive Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Advertising-Account-Executive',
    # },
    # {
    #     'scid': 2117,
    #     'table_name': 'assistant_accounts',
    #     'sub_category': 'Assistant Accounts Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Assistant-Accountant',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 81,
    #     'table_name': 'audit',
    #     'sub_category': 'Audit Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Audit',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 96,
    #     'table_name': 'banking',
    #     'sub_category': 'Banking Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Banking',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 2118,
    #     'table_name': 'bookkeeping_clerk',
    #     'sub_category': 'Bookkeeping Clerk Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Bookkeeping-Clerk',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 1889,
    #     'table_name': 'clerk_accounts_payable',
    #     'sub_category': 'Clerk Accounts Payable Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Accounts-Payable-Clerk',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 82,
    #     'table_name': 'cost_accounting',
    #     'sub_category': 'Cost Accounting Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Cost-Accounting',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 1689,
    #     'table_name': 'executive_accounts',
    #     'sub_category': 'Executive Accounts Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Executive-Account',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 1902,
    #     'table_name': 'juniro_accountant',
    #     'sub_category': 'Junior Accountant Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Junior-Accountant',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 1690,
    #     'table_name': 'key_account_managers',
    #     'sub_category': 'Key Account Managers Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Key-Account-Managers',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 2119,
    #     'table_name': 'payroll_assistant',
    #     'sub_category': 'Payroll Assistant Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Payroll-Assistant',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 2120,
    #     'table_name': 'payroll_specialist',
    #     'sub_category': 'Payroll Specialist Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Payroll-Specialist',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 1688,
    #     'table_name': 'secretary_accountant',
    #     'sub_category': 'Secretary Accountant Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Assistant-Accounts-Officer',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 1903,
    #     'table_name': 'senior_accountant',
    #     'sub_category': 'Senior Accountant Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Senior-Accountant',
    #     'category': 'Accounting',
    #     'category_url': 'https://interviewquestionsanswers.org/Accounting',
    # },
    # {
    #     'scid': 1891,
    #     'table_name': 'branch_manager',
    #     'sub_category': 'Branch Manager Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Branch-Manager',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 444,
    #     'table_name': 'business_administration_mba',
    #     'sub_category': 'Business Administration (MBA) Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_MBA-M-dot-B-dot-A-Master-Business-Administration',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 2121,
    #     'table_name': 'child_attendant',
    #     'sub_category': 'Child Attendant Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Child-Attendant',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 2122,
    #     'table_name': 'child_care_center_director',
    #     'sub_category': 'Child Care Center Director Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Child-Care-Center-Director',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 2125,
    #     'table_name': 'file_clerk_interview',
    #     'sub_category': 'File Clerk Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_File-Clerk',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 1607,
    #     'table_name': 'manager_administration_interview',
    #     'sub_category': 'Manager Administration Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Manager-Administration',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 2128,
    #     'table_name': 'office_administrator',
    #     'sub_category': 'Office Administrator Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Office-Administrator',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 2129,
    #     'table_name': 'office_coordinator_interview',
    #     'sub_category': 'Office Coordinator Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Office-Coordinator',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 2130,
    #     'table_name': 'program_coordinator_interview',
    #     'sub_category': 'Program Coordinator Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Program-Coordinator',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    # {
    #     'scid': 2131,
    #     'table_name': 'program_manager_interview',
    #     'sub_category': 'Program Manager Interview',
    #     'sub_category_link': 'https://interviewquestionsanswers.org/_Program-Manager',
    #     'category': 'Administration',
    #     'category_url': 'https://interviewquestionsanswers.org/Administration',
    # },
    {
        'scid': 2131,
        'table_name': 'program_manager_interview',
        'sub_category': 'Program Manager Interview',
        'sub_category_link': 'https://interviewquestionsanswers.org/_Program-Manager',
        'category': 'Administration',
        'category_url': 'https://interviewquestionsanswers.org/Administration',
    },
]